export enum chatActionTypes {
  ADD_MESSAGE = "ADD_MESSAGE",
  SET_UUID = "SET_UUID",
  SET_MESSAGES = "SET_MESSAGES",
  MODIFY_MESSAGE = "MODIFY_MESSAGE",
  ADD_MORE_MESSAGES_AT_TOP = "ADD_MORE_MESSAGES_AT_TOP",
  MODIFY_SCROLL_HEIGHT = "MODIFY_SCROLL_HEIGHT",
  UPDATE_FIRST_MESSAGE_UID = "UPDATE_FIRST_MESSAGE_UID",
  SET_CHAT_TABS = "SET_CHAT_TABS",
}
